<h1>Invite user</h1>


<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('class', 'form-horizontal');
?>

<div class="row">
	<div class="col-md-12">

		<?php echo $this->form()->openTag($form);?>
			<div class="form-group">
				<label class="col-sm-3 col-lg-2 control-label"><?php echo $form->get('email')->getOption('label')?></label>
				<div class="col-sm-9 col-lg-10 controls">
					<?php echo $this->formInput($form->get('email')->setAttribute('class', 'form-control'));?>
					<?php echo $this->formElementErrors($form->get('email'));?>
			  		<span class="help-inline">E-mail is also username of new user</span>
			   	</div>
			</div>
			<div class="form-group">
				<label class="col-sm-3 col-lg-2 control-label"><?php echo $form->get('password')->getOption('label')?></label>
				<div class="col-sm-9 col-lg-10 controls">
					<?php echo $this->formInput($form->get('password')->setAttribute('class', 'form-control'));?>
					<?php echo $this->formElementErrors($form->get('password'));?>
			  		<span class="help-inline">Password for a new user</span>
			   	</div>
			</div>
			<div class="form-group">
				<label class="col-sm-3 col-lg-2 control-label"><?php echo $form->get('role')->getOption('label')?></label>
				<div class="col-sm-9 col-lg-3 controls">
					<?php echo $this->formSelect($form->get('role')->setAttribute('class', 'form-control'));?>
					<?php echo $this->formElementErrors($form->get('role'));?>
			  		<span class="help-inline">Role of the new user</span>
			   	</div>
			</div>
			<div class="form-group">
				<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2">
			   		<button type="submit" class="btn btn-primary"><i class="icon-ok"></i> <?php echo $form->get('submit')->getValue()?></button>
			   		<a href="<?php echo $this->url('users')?>" class="btn btn-link">Cancel</a>
				</div>
			</div>
		<?php echo $this->form()->closeTag() ?>

	</div>
</div>