<h3><?php echo $this->translate('Unsubscribe')?></h3>

<p>
	<?php echo $this->translate('This will unsubscribe you from list:')?>
</p>

<?php echo $this->FlashMessenger()->render()?>

<br />

<?php if($this->testing){?>
	<div class="well">
		<p>
			<?php echo $this->translate('Note: This is campaign testing, unsubscribe is disabled.')?>
		</p>
	</div>
<?php } else {?>
	<a href="<?php echo $this->url('public/unsubscribe', array('id' => $this->id, 'campaign_id' => $this->campaign_id))?>?confirm" class="btn btn-default"><?php echo $this->translate('Unsubscribe')?></a>
<?php }?>