<?php echo $this->partial('application/campaigns/report-menu.phtml')?>

<h3>Demographics</h3>
<?php 
// BUILD CHART DATA
$mapData = array();
foreach($this->locations['list'] as $country => $region){
	$mapData[] = "['".$country."', ".$region['count']."]";
}
?>
<script type='text/javascript' src='https://www.google.com/jsapi'></script>
    <script type='text/javascript'>
     google.load('visualization', '1', {'packages': ['geochart']});
     google.setOnLoadCallback(drawRegionsMap);

      function drawRegionsMap() {
        var data = google.visualization.arrayToDataTable([
          ['Country', 'Opens'],
          <?php echo join(",", $mapData)?>
        ]);

        var options = {};

        var chart = new google.visualization.GeoChart(document.getElementById('chart_div'));
        chart.draw(data, options);
    };
    </script>
    
<div class="row">
	<div class="col-md-12">
		<div id="chart_div" style="width: 100%; height: 500px;"></div>
		<br /><br />
	</div>
</div>

<div class="row">
	<div class="col-md-12">
		<div class="well">

			<div class="row">
				<div class="col-md-7">
					<div id="countriesChart" class="chart"></div>
				</div>
				<div class="col-md-5">
					<table class="table table-striped table-hover fill-head table-responsive chartleft">
					  		<tbody>
					  			<?php $t=0;foreach($this->locations['list'] as $country => $region){ $t++;?>
						  			<tr>
						  				<td><b><a href="#" data-target="tar_<?php echo $t?>"><?php echo ($country?$country:'N/A')?></a></b></td>
						  				<td><?php echo $region['count']?></td>
						  				<td></td>
						  			</tr>
						  			<?php foreach($region['regions'] as $r_name => $r_props){?>
							  			<tr class="sub tar_<?php echo $t?>">
							  				<td><b><?php echo ($r_name?$r_name:'N/A')?></b></td>
							  				<td><?php echo $r_props['count']?></td>
							  				<td></td>
							  			</tr>
					  				<?php }?>
					  			<?php }?>
					  		</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>

<?php 
// BUILD CHART DATA

$locJson = array();
$c = 0;
$other = 0;
$l_cats = array();
foreach($this->locations['list'] as $name => $family){
	if($family['percent']<3){
		if(!in_array("'Other'", $l_cats)){
			$l_cats[] = "'Other'";
		}
	
		$other += $family['percent'];
	} else {
		$l_cats[] = "'".$name."'";
		$json = "{y: ".$family['percent'].", color: colors[".$c."], drilldown: { name: 'Versions',";
		$cats = array();
		$data = array();
		$other_v = 0;
		foreach($family['regions'] as $version => $versionprops){
			if($versionprops['percent'] < 1){
				$other_v += $versionprops['percent'];
			} else {
				$cats[] = "'".$version."'";
				$data[] = $versionprops['percent'];
			}
		}
		if($other_v){
			$cats[] = "'Other'";
			$data[] = $other_v;
		}
		$json .= 'categories:['.join(',', $cats).'],';
		$json .= 'data:['.join(',', $data).'],';
		$json .= 'color: colors['.$c.']}}';
		$locJson[] = $json;
		$c++;
	}
}
// add other
if($other){
	$json = "{y: ".$other.", color: colors[".$c."], drilldown: { name: 'Versionso',";
	$cats = array("'Other'");
	$data = array($other);
	$json .= 'categories:['.join(',', $cats).'],';
	$json .= 'data:['.join(',', $data).'],';
	$json .= 'color: colors['.$c.']}}';
	$locJson[] = $json;
}
?> 

<script>
$(function () {

	$('.chartleft a').click(function(){
		$('.'+$(this).data('target')).toggle()
		return false;
	});
	
	var colors = Highcharts.getOptions().colors,
    categories = [<?php echo join(",", $l_cats)?>],
    name = 'Browser brands',
    data = [<?php echo join(',', $locJson);?>];
		
		
	// Build the data arrays
	var browserData = [];
	var versionsData = [];
	for (var i = 0; i < data.length; i++) {
	
	    // add browser data
	    browserData.push({
	        name: categories[i],
	        y: data[i].y,
	        color: data[i].color
	    });
	
	    // add version data
	    for (var j = 0; j < data[i].drilldown.data.length; j++) {
	        var brightness = 0.2 - (j / data[i].drilldown.data.length) / 5 ;
	        versionsData.push({
	            name: data[i].drilldown.categories[j],
	            y: data[i].drilldown.data[j],
	            color: Highcharts.Color(data[i].color).brighten(brightness).get()
	        });
	    }
	}

	// Create the chart
    $('#countriesChart').highcharts({
        chart: {
            type: 'pie'
        },
        title: {
            text: ''
        },
        yAxis: {
            title: {
                text: 'Total percent market share'
            }
        },
        plotOptions: {
            pie: {
                shadow: false,
                center: ['50%', '50%']
            }
        },
        credits: {
            enabled: false
        },
        tooltip: {
    	    valueSuffix: '%'
        },
        series: [{
            name: 'Browsers',
            data: browserData,
            size: '60%',
            dataLabels: {
                formatter: function() {
                    return this.y > 4 ? this.point.name : null;
                },
                color: 'white',
                distance: -30
            }
        }, {
            name: 'Versions',
            data: versionsData,
            size: '80%',
            innerSize: '60%',
            dataLabels: {
                formatter: function() {
                    // display only if larger than 1
                	if(this.point.name=='')
                    	this.point.name = 'Unknown';
                    return this.y > 2 ? '<b>'+ this.point.name +':</b> '+ this.y +'%'  : null;
                }
            }
        }]
    });

});
</script>