<?php echo $this->campaign->html_text?>

<?php if($this->log){?>

<?php
$total = 0; 
foreach($this->log as $row){
	$total += $row['total'];
}?>
<style>
.clickrate{
	position: absolute !important;
	display: block !important;
	background-color: black !important;
	opacity: 0.6 !important;
	padding: 5px !important;
	color: white !important;
	font-size: 12px !important;
	text-transform: none !important;
	font-family: Arial !important;
	line-height: 12px !important;
	font-weight: bold !important;
	width: 80px !important;
	height: 12px;
	z-index: 99999;
}
.clickrate .bg{
	background-color: green !important;
	height: 22px;
	position: absolute;
	top: 0;
	left: 0;
}
.clickrate span{
	position: relative;
}
</style>
<script type="text/javascript" src="<?php echo $this->basePath()?>/js/jquery.min.js"></script>
<script>
$(function () {
	<?php foreach($this->log as $row){?>
	highlightLink($('a[href="<?php echo $row[0]->msg?>"]'), <?php echo $row['total']?>, <?php echo round(($row['total']/$total)*100, 2)?>);
	<?php }?>

	function highlightLink(element, count, percent){
		element.css('position', 'relative');
		element.append('<div class="clickrate"><div class="bg" style="width:' + percent + '%"></div><span>' + percent + '%&nbsp;(' + count + ')</span></div>');
	}
});
</script>
<?php }?>