<?php echo $this->partial('application/campaigns/report-menu.phtml')?>

<h3>Share this campaign report</h3>

<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('class', 'form-horizontal');
?>

<?php if($this->FlashMessenger()->getMessages()){?><div class="alert alert-success"><?php echo $this->FlashMessenger()->render()?></div><?php }?>

<div class="row">
	<div class="col-md-12">

		<?php echo $this->form()->openTag($form);?>
		<div class="row">
			<div class="col-md-12">
				<div class="form-group">
					<label class="col-sm-3 col-lg-2 control-label"><?php echo $form->get('password')->getOption('label')?></label>
					<div class="col-sm-9 col-lg-10 controls">
						<?php echo $this->formInput($form->get('password')->setAttribute('class', 'form-control'));?>
						<?php echo $this->formElementErrors($form->get('password'));?>
				  		<span class="help-inline">Report will be protected by this password, password will be sent along with report link</span>
				   	</div>
				</div>
			</div>

			<div class="col-md-12">
				<div class="form-group">
					<label class="col-sm-3 col-lg-2 control-label"><?php echo $form->get('recipient')->getOption('label')?></label>
					<div class="col-sm-9 col-lg-10 controls">
						<?php echo $this->formInput($form->get('recipient')->setAttribute('class', 'form-control'));?>
						<?php echo $this->formElementErrors($form->get('recipient'));?>
				  		<span class="help-inline"></span>
				   	</div>
				</div>
			</div>

				<div class="form-group">
					<div class="col-sm-9 col-lg-10">
				   		<button type="submit" class="btn btn-primary"><i class="icon-ok"></i> <?php echo $form->get('submit')->getValue()?></button>
				   		<!-- <a href="<?php echo $this->url('brands')?>" class="btn btn-link">Cancel</a> -->
					</div>
				</div>
			</div>

		</div>
		<?php echo $this->form()->closeTag() ?>

	</div>
</div>