<h1>Edit list</h1>

<?php
$form = $this->form;
$form->prepare();
echo $this->form()->render($form);
?>

<div class="row-fluid">
	<div class="span12">
		<h2>Subscribe settings</h2><br/>
	</div>
</div>

<div class="row-fluid">

	<div class="span4">

		<label class="control-label"><strong>List type</strong></label>

		<div class="well">
			<p>If you select double opt-in, users will be required to click a link in a confirmation email they'll receive when they sign up via the subscribe form or API.</p>

			<p>
				<div class="btn-group" data-toggle="buttons-radio">
					<a href="javascript:void(0)" title="" class="btn" id="single"><i class="icon icon-angle-right"></i> Single Opt-In</a>
					<a href="javascript:void(0)" title="" class="btn" id="double"><i class="icon icon-double-angle-right"></i> Double Opt-In</a>
				</div>

						<script type="text/javascript">
							$(document).ready(function() {
																$("#single").button('toggle');
								$("#opt_in").val("0");

								$("#single").click(function(){
									$("#opt_in").val("0");
								});
								$("#double").click(function(){
									$("#opt_in").val("1");
								});
							});
						</script>
			</p>
		</div>

		<label class="control-label" for="subscribed_url"><strong>Subscribe success page</strong></label>
		<div class="well">
			<p>When users subscribe through the subscribe form, they'll be sent to a generic subscription confirmation page. To redirect users to a page of your preference, enter the link below. If you chose double opt-in as your List Type, this page will tell them a confirmation email has been sent to them.</p>
			<label class="control-label" for="subscribed_url">Page URL</label>
			<div class="control-group">
				<div class="controls">
					<input type="text" class="input-xlarge" id="subscribed_url" name="subscribed_url" placeholder="http://" style="width: 98%;" value="">
				</div>
			</div>
		</div>

		<label class="control-label" for="subscribed_url"><strong>Subscription confirmed page</strong> (only applies for double opt-ins)</label>
		<div class="well">
			<p>If your List Type is double opt-in, users who clicked the confirmation URL will be sent to a generic confirmation page. To redirect users to a page of your preference, enter the link below.</p>
		    <label class="control-label" for="confirm_url">Page URL</label>
			<div class="control-group">
				<div class="controls">
			    	<input type="text" class="input-xlarge" id="confirm_url" name="confirm_url" placeholder="http://" style="width: 98%;" value="">
			    </div>
			</div>
		</div>

	</div>

	<div class="span8">

		<div class="control-group">
			<div class="controls">
				<label class="checkbox">
					<input type="checkbox" id="thankyou_email" name="thankyou_email" >
					Send user a thank you email after they subscribe through the subscribe form or API?
				</label>
			</div>
		</div>

		<label class="control-label" for="thankyou_subject"><strong>Thank you email subject</strong></label>
		<div class="control-group">
			<div class="controls">
				<input type="text" class="input-xlarge" id="thankyou_subject" name="thankyou_subject" placeholder="Email subject" style="width: 98%;" value="">
			</div>
		</div>

		<label class="control-label" for="thankyou_message"><strong>Thank you email message</strong></label>
		<div class="control-group">
			<div class="controls">
				<textarea class="input-xlarge" id="thankyou_message" name="thankyou_message" rows="10" placeholder="Email message"></textarea>
			</div>
		</div>

		<br/>

		<label class="control-label" for="confirmation_subject"><strong>Confirmation email subject</strong> (only applies for double opt-ins)br/><em>* A generic subject line will be used if you leave this field empty.</em></label>
		<div class="control-group">
		  	<div class="controls">
				<input type="text" class="input-xlarge" id="confirmation_subject" name="confirmation_subject" placeholder="Subject of confirmation email" style="width: 98%;" value="">
			</div>
		</div>

		<label class="control-label" for="confirmation_email"><strong>Double Opt-In confirmation message</strong> (only applies for double opt-ins)<br/><em>* A generic email message will be used if you leave this field empty.</em><br/><em>* Don't forget to include the confirmation link tag </em><code>[confirmation_link]</code><em> somewhere in your message</em>.</label>
		<div class="control-group">
			<div class="controls">
				<textarea class="input-xlarge" id="confirmation_email" name="confirmation_email" rows="10" placeholder="Email message"></textarea>
			</div>
		</div>

	</div>

</div>

<div class="row-fluid">
	<div class="span12">
		<h2>Unsubscribe settings</h2><br/>
	</div>
</div>

<div class="row-fluid">

	<div class="span4">
		<label class="control-label"><strong>Unsubscribe user</strong></label>
		<div class="well">
			<p>When a user unsubscribes from a newsletter or through the API, choose whether to unsubscribe them from this list only, or unsubscribe them from all lists in this brand.</p>
		    <p>
				<div class="btn-group" data-toggle="buttons-radio">
					<a href="javascript:void(0)" title="" class="btn" id="this-list"><i class="icon icon-minus"></i> Only this list</a>
					<a href="javascript:void(0)" title="" class="btn" id="all-list"><i class="icon icon-reorder"></i> All lists</a>
				</div>
						<script type="text/javascript">
							$(document).ready(function() {
																$("#all-list").button('toggle');
								$("#unsubscribe_all_list").val("1");

								$("#this-list").click(function(){
									$("#unsubscribe_all_list").val("0");
								});
								$("#all-list").click(function(){
									$("#unsubscribe_all_list").val("1");
								});
							});
						</script>
			</p>
		</div>

		<label class="control-label" for="unsubscribed_url"><strong>Unsubscribe confirmation page</strong></label>
		<div class="well">
			<p>When users unsubscribe from a newsletter, they'll be sent to a generic unsubscription confirmation page. To redirect users to a page of your preference, enter the link below.</p>
			<label class="control-label" for="subscribed_url">Page URL</label>
			<div class="control-group">
				<div class="controls">
					<input type="text" class="input-xlarge" id="unsubscribed_url" name="unsubscribed_url" placeholder="http://" style="width: 98%;" value="">
				</div>
			</div>
		</div>
	</div>

	<div class="span8">

		<div class="control-group">
			<div class="controls">
				<label class="checkbox">
					<input type="checkbox" id="goodbye_email" name="goodbye_email" >
					Send user a confirmation email after they unsubscribe from a newsletter or through the API?
				</label>
	        </div>
		</div>

		<label class="control-label" for="goodbye_subject"><strong>Goodbye email subject</strong></label>
		<div class="control-group">
			<div class="controls">
				<input type="text" class="input-xlarge" id="goodbye_subject" name="goodbye_subject" placeholder="Email subject" style="width: 98%;" value="">
			</div>
		</div>

		<label class="control-label" for="goodbye_message"><strong>Goodbye email message</strong></label>
		<div class="control-group">
			<div class="controls">
				<textarea class="input-xlarge" id="goodbye_message" name="goodbye_message" rows="10" placeholder="Email message"></textarea>
			</div>
		</div>

		<input type="hidden" name="id" value="6">
		<input type="hidden" name="list" value="47">
		<input type="hidden" name="opt_in" id="opt_in" value="">
		<input type="hidden" name="unsubscribe_all_list" id="unsubscribe_all_list" value="">

	</div>

</div>