<h1>"<?php echo $this->list->name?>" list</h1>

<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <li class="active"><a href="#">Stats</a></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Manage subscribers <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="#">View subscribers</a></li>
          <li><a href="<?php echo $this->url('lists/show/add-subscribers', array('id' => $this->list->id))?>">Add subscribers</a></li>
          <li><a href="<?php echo $this->url('lists/show/remove-subscribers', array('id' => $this->list->id))?>">Remove subscribers</a></li>
        </ul>
      </li>
      <li><a href="#">Import</a></li>
      <li><a href="#">Settings</a></li>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>