<h1>Remove subsribers</h1>

<h2>Delete email per line (hard delete)</h2><br/>

<form method="POST" accept-charset="utf-8" class="form-vertical" enctype="multipart/form-data" id="line-import-form">


	<label class="control-label" for="line">Email to delete</label>
	<div class="control-group">
		<div class="controls">
			<textarea class="input-xlarge" id="line" name="line" rows="10" placeholder="Eg. hermanmiller@gmail.com"></textarea>
		</div>
	</div>

	<br/>
	<button type="submit" class="btn btn-inverse">Delete</button>
</form>