<h1>Show list</h1>

<h2>List subscribers</h2>

<script src="<?php echo $this->basePath()?>/js/highcharts/highcharts.js"></script>

<script type="text/javascript">
	var month=new Array();
	month[0]="Jan";month[1]="Feb";month[2]="Mar";month[3]="Apr";month[4]="May";month[5]="Jun";month[6]="Jul";month[7]="Aug";month[8]="Sep";month[9]="Oct";month[10]="Nov";month[11]="Dec";

	var chart;
	$(document).ready(function() {
		Highcharts.setOptions({
	        colors: ['#468847', '#B94A48', '#333333']
	    });
		chart = new Highcharts.Chart({
			chart: {
				renderTo: 'container',
				type: 'areaspline',
				marginBottom: 25
			},
			title: {
				text: false
			},
			subtitle: {
				text: false
			},
			xAxis: {
				categories: [
				month[9]+" 12",month[10]+" 12",month[11]+" 12",month[0]+" 13",month[1]+" 13",month[2]+" 13",month[3]+" 13",month[4]+" 13",month[5]+" 13",month[6]+" 13",month[7]+" 13",month[8]+" 13"						]
			},
			yAxis: {
				title: {
					text: false
				},
				plotLines: [{
					value: 0,
					width: 1,
					color: '#808080'
				}]
			},
			plotOptions: {
				line: {
					stacking: 'normal'
				},
				series: {
	                marker: {
	                    enabled: false
	                }
	            }
			},
			tooltip: {
				formatter: function() {
						return '<b>'+ this.series.name +'</b><br/>'+
						this.x +': '+ this.y;
				}
			},
			legend: {
				enabled: false
			},
			credits: {
                enabled: false
            },
			series: [{
                name: 'Subscribers',
                data: [
                0,0,0,0,105894,105896,105896,105956,105961,105967,106030,106043		                ]
            }]
		});
	});
</script>
// demo graph
<div id="container" style="min-height:200px;margin:0 0 30px 0;"></div>

<table class="table table-striped">
	<thead>
		<tr>
			<td>name</td>
			<td>email</td>
			<td>last activity</td>
			<td>status</td>
			<td>un/re-subscribe</td>
			<td>delete</td>
		</tr>
	</thead>
	<tbody>
	<?php foreach($this->subscribers as $subscriber_connection){?>
	<tr>
		<td>
			<?php echo $subscriber_connection->subscriber->name?>
		</td>
		<td>
			<?php echo $subscriber_connection->subscriber->email?>
		</td>
		<td>
			//todo last activity
		</td>
		<td>
			<?php echo $this->userStatus($subscriber_connection->status)?>
		</td>
		<td>
			<?php if($subscriber_connection->status==1){?>
				<a href="<?php echo $this->url('lists/unsubscribe', array('connection_id' => $subscriber_connection->id))?>">un-subscribe</a>
			<?php } else {?>
				<a href="<?php echo $this->url('lists/resubscribe', array('connection_id' => $subscriber_connection->id))?>">re-subscribe</a>
			<?php }?>
		</td>
		<td>
			<a href="<?php echo $this->url('lists/delete-user', array('connection_id' => $subscriber_connection->id))?>">delete</a>
		</td>
	</tr>
	<?php }?>
	</tbody>
</table>