<script src="<?php echo $this->basePath()?>/js/highcharts/highcharts.js"></script>

<?php echo $this->partial('application/lists/list-menu.phtml')?>

<?php echo $this->partial('partials/graph', array('id' => 'totalYearStats', 'stats' => $this->totalYearStats, 'colors' => array("'#468847'", "'#B94A48'", "'#333333'")))?>

<table class="table table-striped">
	<thead>
		<tr>
			<td>name</td>
			<td>email</td>
			<td>last activity</td>
			<td>status</td>
			<td>un/re-subscribe</td>
			<td>delete</td>
		</tr>
	</thead>
	<tbody>
	<?php foreach($this->subscribers as $subscriber_connection){?>
	<tr>
		<td>
			<?php echo $subscriber_connection->subscriber->name?>
		</td>
		<td>
			<?php echo $subscriber_connection->subscriber->email?>
		</td>
		<td>
			<?php echo $subscriber_connection->last_activity_at->format('Y-m-d H:i:s');?>
		</td>
		<td>
			<?php echo $this->userStatus($subscriber_connection->status)?>
		</td>
		<td>
			<?php if($subscriber_connection->status==1){?>
				<a href="<?php echo $this->url('lists/unsubscribe', array('connection_id' => $subscriber_connection->id))?>">un-subscribe</a>
			<?php } else {?>
				<a href="<?php echo $this->url('lists/resubscribe', array('connection_id' => $subscriber_connection->id))?>">re-subscribe</a>
			<?php }?>
		</td>
		<td>
			<a href="<?php echo $this->url('lists/delete-user', array('connection_id' => $subscriber_connection->id))?>">delete</a>
		</td>
	</tr>
	<?php }?>
	</tbody>
</table>