<table class="table table-striped table-hover fill-head table-responsive lists">
	<thead>
		<tr>
			<td class="hidden-xs">ID</td>
			<td>list name</td>
			<td class="hidden-xs">active</td>
			<td class="hidden-xs">unsubscribed</td>
			<td class="hidden-xs">bounced</td>
			<td class="hidden-xs">complaints</td>
			<td class="edit"></td>
			<td class="split hidden-xs"></td>
			<td class="delete"></td>
		</tr>
	</thead>
	<tbody>
		<?php foreach($this->brand->lists as $list){?>
		<tr>
			<td class="hidden-xs">
				<?php echo $list->id?>
			</td>
			<td>
				<a href="<?php echo $this->url('lists/show', array('id' => $list->id))?>"><?php echo $list->name?></a>
			</td>
			<td class="hidden-xs">
				<?php echo $listsService->getActiveUsersCount($list->id) ?>
			</td>
			<td class="hidden-xs">
				<?php echo $listsService->getUnsubscribedUsersCount($list->id)?>
			</td>
			<td class="hidden-xs">
				<?php echo $listsService->getBouncedUsersCount($list->id)?>
			</td>
			<td class="hidden-xs">
				<?php echo $listsService->getComplainedUsersCount($list->id)?>
			</td>
			<td class="edit">
				<a href="<?php echo $this->url('lists/edit', array('id' => $list->id))?>"><span class="glyphicon glyphicon-pencil"></span> Edit</a>
			</td>
			<td class="split hidden-xs">
				<a href="<?php echo $this->url('lists/split', array('id' => $list->id))?>"><span class="glyphicon glyphicon-resize-full"></span> Split</a>
			</td>
			<td class="delete">
				<a href="<?php echo $this->url('lists/delete', array('id' => $list->id))?>"><span class="glyphicon glyphicon-trash"></span> Delete</a>
			</td>
		</tr>
		<?php }?>
	</tbody>
</table>