<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Mailing Machinegun | Massimo Filippi')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/base.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-modal.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-modal-bs3patch.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-switch.css')
                        ->prependStylesheet($this->basePath() . '/assets/font-awesome/css/font-awesome.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/less-1.4.1.min.js')
                                      ->prependFile($this->basePath() . '/js/bootstrap-modal.js')
                                      ->prependFile($this->basePath() . '/js/bootstrap-modalmanager.js')
                                      ->prependFile($this->basePath() . '/js/bootstrap-switch.min.js')
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js') ?>

		<!-- Fonts -->
		<link href='http://fonts.googleapis.com/css?family=Open+Sans:300,400&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
		<link href='http://fonts.googleapis.com/css?family=Dosis:200,300,700' rel='stylesheet' type='text/css'>

    </head>
    <body>
		
		<?php if(!$this->publicReport){?>
		<div id="navbar">

	  		<button type="button" class="navbar-toggle navbar-btn collapsed" data-toggle="collapse" data-target="#sidebar">
				<span class="icon-reorder"></span>
			</button>

	  		<a href="<?php echo $this->url('home') ?>" id="logo"></a>

	  		<div id="userNav">
				<div class="dropdown">
				  <a data-toggle="dropdown" href="#" class="trigger"><span class="glyphicon glyphicon-cog"></span> <span class="textlabel">Massimo Filippi</span> <span class="caret"></span></a>
				  <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
				  	<li><a href="<?php echo $this->url('settings') ?>"><span class="glyphicon glyphicon-wrench"></span> Machinegun settings</a></li>
				  	<li><a href="<?php echo $this->url('settings') ?>"><span class="glyphicon glyphicon-lock"></span> Profile settings</a></li>
				  	<li><a href="<?php echo $this->url('users') ?>"><span class="glyphicon glyphicon-user"></span> Manage users</a></li>
				  	<li><a href="<?php echo $this->url('zfcuser/logout') ?>"><span class="glyphicon glyphicon-off"></span> Logout</a></li>
				  </ul>
				</div>
	  		</div>

	  		<ul id="topMenu">
	  			<li><a href="<?php echo $this->url('home') ?>" <?php if($this->active=='dashboard'){?>class="active"<?php }?>><span class="glyphicon glyphicon-dashboard"></span> Dashboard</a></li>
	  			<li><a href="<?php echo $this->url('brands') ?>" <?php if($this->active=='brands'){?>class="active"<?php }?>><span class="glyphicon glyphicon-folder-open"></span> Brands</a></li>
	  		</ul>

	  	</div>
	  	<?php }?>

	  	<div id="container">

		  	<div id="sidebar" class="navbar-collapse collapse">
		  		<!--
	  			<ul>
	  				<li><a href="" class="active"><span class="glyphicon glyphicon-list"></span> Campaigns list</a></li>
	  				<li><a href=""><span class="glyphicon glyphicon-pencil"></span> Create new campaign</a></li>
	  				<li><a href=""><span class="glyphicon glyphicon-user"></span> Lists & subscribers</a></li>
	  				<li><a href=""><span class="glyphicon glyphicon-tasks"></span> Reports <span class="badge pull-right">42</span></a></li>
	  			</ul>
	  			 -->
	  			<?php if(!$this->publicReport){?>
					<?php if(!$this->menu){?>
						<?php echo $this->partial('partials/siderbar-dashboard', array('mandrillInfo' => $this->mandrillInfo))?>
		  			<?php } elseif($this->brand_id) {?>
		  				<?php echo $this->partial('partials/'.$this->menu, array('brand_id' => $this->brand_id, 'submenu_active' => $this->submenu_active))?>
		  			<?php }?>
				<?php } else {?>
					<div style="padding: 15px; color: #fff">
						<p>This is public report</p>
						<p><a href="<?php echo $this->url('public/report/logout', array('id' => $this->campaign_id))?>" class="btn btn-default">logout</a></p>
					</div>
				<?php }?>
	  		</div>

	  		<div id="main-content">

	  			<div class="row">
	  				<div class="col-md-12">

	  					<?php echo $this->content; ?>

	  				</div>
				</div>

	  		</div>

	  	</div>

	  	<!-- MODALS -->
		<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		    <div class="modal-dialog">
		      <div class="modal-content">
		        <div class="modal-header">
		          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		          <h4 class="modal-title">Emergency brake</h4>
		        </div>
		        <div class="modal-body">
		        	<div class="bs-callout bs-callout-danger">
				      <h4>Hold on! Be carefull!</h4>
				      <p>This will clear your backlog. All sheduled e-mails will be removed from queue! This action connot be undone!</p>
				    </div>
		        </div>
		        <div class="modal-footer">
		          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
		          <button type="button" class="btn btn-danger">Clear backlog</button>
		        </div>
		      </div><!-- /.modal-content -->
		    </div><!-- /.modal-dialog -->
		</div><!-- /.modal -->

    </body>
</html>
