<!-- Dashboard scripts -->
<script src="<?php echo $this->basePath()?>/js/highcharts/highcharts.js"></script>

<div class="row">

	<div class="col-md-12">

		<h1>Brands</h1>

		<?php if($this->FlashMessenger()->getMessages()){?><div class="alert alert-success"><?php echo $this->FlashMessenger()->render()?></div><?php }?>

		<div class="well brands">

			<table class="table table-striped table-hover fill-head table-responsive">
				<thead>
					<tr>
						<th>Brand</th>
						<th>Stats</th>
						<th>Lists</th>
						<th>Subscribers</th>
						<th class="edit"></th>
						<th class="delete"></th>
					</tr>
				</thead>
				<tbody>
					<?php foreach($this->brands as $brand){?>
					<tr>
						<td>
							<a href="<?php echo $this->url('brands/show', array('id' => $brand->id))?>">
								<img src="https://getfavicon.appspot.com/http://www.<?php echo array_pop(explode('@', $brand->from_email))?>?defaulticon=http://userbase.mfcc.cz/img/default-favicon.png" style="margin:-3px 5px 0 0; width:16px; height: 16px;">
								<?php echo $brand->name?>
							</a>
						</td>
						<td>
							<span><?php echo count($brand->campaigns)?> campaigns</span>
						</td>
						<td></td>
						<td></td>
						<td><a href="<?php echo $this->url('brands/edit', array('id' => $brand->id))?>"><span class="glyphicon glyphicon-pencil"></span> Edit</a></td>
						<td><a href="<?php echo $this->url('brands/delete', array('id' => $brand->id))?>"><span class="glyphicon glyphicon-trash"></span> Delete</a></td>
					</tr>
					<?php }?>
				</tbody>
			</table>

			<a href="<?php echo $this->url('brands/add')?>" class="btn btn-primary">Add brand</a>

		</div>

	</div>

</div>

<div class="row">

	<div class="col-md-12">

		<h1>Brands activity</h1>

		<div class="well brands">

			<div id="brandsActivity" style="min-width: 310px; height: 400px; margin: 0 auto"></div>

		</div>

	</div>

</div>

<script>
$(function () {
    $('#brandsActivity').highcharts({
        chart: {
            type: 'area'
        },
        title: {
            text: 'US and USSR nuclear stockpiles'
        },
        subtitle: {
            text: 'Source: <a href="http://thebulletin.metapress.com/content/c4120650912x74k7/fulltext.pdf">'+
                'thebulletin.metapress.com</a>'
        },
        xAxis: {
            labels: {
                formatter: function() {
                    return this.value; // clean, unformatted number for year
                }
            }
        },
        yAxis: {
            title: {
                text: 'Nuclear weapon states'
            },
            labels: {
                formatter: function() {
                    return this.value / 1000 +'k';
                }
            }
        },
        tooltip: {
            pointFormat: '{series.name} produced <b>{point.y:,.0f}</b><br/>warheads in {point.x}'
        },
        plotOptions: {
            area: {
                pointStart: 1940,
                marker: {
                    enabled: false,
                    symbol: 'circle',
                    radius: 2,
                    states: {
                        hover: {
                            enabled: true
                        }
                    }
                }
            }
        },
        series: [{
            name: 'USA',
            data: [null, null, null, null, null, 6 , 11, 32, 110, 235, 369, 640,
                1005, 1436, 2063, 3057, 4618, 6444, 9822, 15468, 20434, 24126,
                27387, 29459, 31056, 31982, 32040, 31233, 29224, 27342, 26662,
                26956, 27912, 28999, 28965, 27826, 25579, 25722, 24826, 24605,
                24304, 23464, 23708, 24099, 24357, 24237, 24401, 24344, 23586,
                22380, 21004, 17287, 14747, 13076, 12555, 12144, 11009, 10950,
                10871, 10824, 10577, 10527, 10475, 10421, 10358, 10295, 10104 ]
        }, {
            name: 'USSR/Russia',
            data: [null, null, null, null, null, null, null , null , null ,null,
            5, 25, 50, 120, 150, 200, 426, 660, 869, 1060, 1605, 2471, 3322,
            4238, 5221, 6129, 7089, 8339, 9399, 10538, 11643, 13092, 14478,
            15915, 17385, 19055, 21205, 23044, 25393, 27935, 30062, 32049,
            33952, 35804, 37431, 39197, 45000, 43000, 41000, 39000, 37000,
            35000, 33000, 31000, 29000, 27000, 25000, 24000, 23000, 22000,
            21000, 20000, 19000, 18000, 18000, 17000, 16000]
        }]
    });
});
</script>

