<h1><b><?php echo $this->brand->name?></b> overview</h1>

<div class="row">
	<div class="col-md-12">
		<div class="well">

			<h2>Brand campaigns</h2>

			<?php if($this->FlashMessenger()->getMessages()){?><div class="alert alert-success"><?php echo $this->FlashMessenger()->render()?></div><?php }?>

			<!-- TODO this to partial -->
			<?php echo $this->partial('partials/table-campaigns',array('brand'=>$this->brand, 'campaignStats'=>$this->campaignStats));?>
			
			<a href="<?php echo $this->url('brands/campaigns', array('id' => $this->brand->id))?>" class="btn btn-primary">Go to campaigns</a>

		</div>
	</div>
</div>

<div class="row">
	<div class="col-md-12">
		<div class="well">

			<h2>Brand lists</h2>

			<?php echo $this->partial('partials/table-lists',array('brand'=>$this->brand, 'listsService'=>$this->listsService));?>

			<a href="<?php echo $this->url('brands/lists', array('id' => $this->brand->id))?>" class="btn btn-primary">Go to lists</a>

			<!--
			<div class="pull-right">
				<a href="<?php echo $this->url('lists/merge', array('brand_id' => $this->brand->id))?>" class="btn btn-primary">Merge</a>
			</div>

			<a href="<?php echo $this->url('lists/add', array('brand_id' => $this->brand->id))?>" class="btn btn-primary">Add list</a>
			 -->

		</div>
	</div>
</div>