<h1>Show brand</h1>

<h2>Brand campaigns</h2>

<table class="table table-striped">
	<thead>
		<tr>
			<td>ID</td>
			<td>campaign title</td>
			<td>recipients (at the time of sending)</td>
			<td>sent</td>
			<td>opens (total/unique)</td>
			<td>clicks (total/unique)</td>
			<td>duplicate</td>
			<td>delete</td>
		</tr>
	</thead>
	<tbody>
	<?php foreach($this->brand->campaigns as $campaign){?>
	<tr>
		<td>
			<?php echo $campaign->id?>
		</td>
		<td>
			<a href="<?php echo $this->url('campaigns/show', array('id' => $campaign->id))?>"><?php echo $campaign->title?></a>
		</td>
		<td>

		</td>
		<td>

		</td>
		<td>

		</td>
		<td>

		</td>
		<td>
			<a href="<?php echo $this->url('campaigns/duplicate', array('id' => $campaign->id))?>">Duplicate (todo)</a>
		</td>
		<td>
			<a href="<?php echo $this->url('campaigns/delete', array('id' => $campaign->id))?>">Delete (todo)</a>
		</td>
	</tr>
	<?php }?>
	</tbody>
</table>

<a href="<?php echo $this->url('campaigns/add', array('brand_id' => $this->brand->id))?>" class="btn btn-primary">Create &amp; send new campaign</a>

<h2>Brand lists</h2>

<table class="table table-striped">
	<thead>
		<tr>
			<td>ID</td>
			<td>list name</td>
			<td>active</td>
			<td>unsubscribed</td>
			<td>bounced</td>
			<td>complaints</td>
			<td>edit</td>
			<td>delete</td>
		</tr>
	</thead>
	<tbody>
	<?php foreach($this->brand->lists as $list){?>
	<tr>
		<td>
			<?php echo $list->id?>
		</td>
		<td>
			<a href="<?php echo $this->url('lists/show', array('id' => $list->id))?>"><?php echo $list->name?></a>
		</td>
		<td>
			<?php echo count($list->getActiveUsers())?>
		</td>
		<td>
			<?php echo count($list->getUnsubscribedUsers())?>
		</td>
		<td>
			<?php echo count($list->getSoftBouncedUsers()) + count($list->getHardBouncedUsers())?>
		</td>
		<td>
			<?php echo count($list->getComplainedUsers())?>
		</td>
		<td>
			<a href="<?php echo $this->url('lists/edit', array('id' => $list->id))?>">Edit</a>
		</td>
		<td>
			<a href="<?php echo $this->url('lists/delete', array('id' => $list->id))?>">Delete</a>
		</td>
	</tr>
	<?php }?>
	</tbody>
</table>

<a href="<?php echo $this->url('lists/add', array('brand_id' => $this->brand->id))?>" class="btn btn-primary">Add list</a>