<!-- Dashboard scripts -->
<script src="<?php echo $this->basePath()?>/js/highcharts/highcharts.js"></script>

<div class="row">
	<div class="col-md-6">

		<h1><?php echo $this->translate('Total Subscribers') ?></h1>

		<div class="well">

			<?php echo $this->partial('partials/graph', array('id' => 'totalYearStats', 'stats' => $this->totalYearStats, 'colors' => array("'#468847'", "'#B94A48'", "'#333333'")))?>

		</div>

	</div>
	<div class="col-md-6">

		<h1><?php echo $this->translate('Sending Volume') ?></h1>

		<div class="well">

			<?php
			$stats = array('print' => array(), 'data' => array());
			foreach($this->sendingVolume as $row){
				$dayParts = explode(' ', $row['time']);
				$date = new DateTime($row['time']);
				if(!in_array("'".$date->format('m-d')."'", $stats['print']))
					$stats['print'][] = "'".$date->format('m-d')."'";
				$stats['data'][$dayParts[0]] += $row['sent'];
			}
			?>

			<?php echo $this->partial('partials/graph', array('id' => 'sendingVolume', 'stats' => $stats, 'name' => 'Volume sent', 'colors' => array("'#468847'", "'#B94A48'", "'#333333'")))?>

		</div>

	</div>
</div>

<div class="row">

	<div class="col-md-12">

		<h1>Webhook status</h1>

		<?php if($this->webhookStatus){?>
			<div class="alert alert-success">
				Webhook is set up. (Webhooks formatting help: <a href="http://help.mandrill.com/entries/24466132-Webhook-Format">http://help.mandrill.com/entries/24466132-Webhook-Format</a>)
			</div>
		<?php } else {?>
			<div class="alert alert-error">
				Webhooks won't work on localhost!
			</div>
			<div class="alert alert-block">
				<h4>Warning!</h4>
				Webhook is not set in Mandrill! You wont get any statistics!
				<br />
				<a href="<?php echo $this->url('hooks/set')?>" class="btn btn-primary">Set webhook now!</a>
			</div>
		<?php }?>

		<h1>Brands</h1>

		<div class="well brands">

			<table class="table table-striped table-hover fill-head table-responsive">
				<thead>
					<tr>
						<th>Brand</th>
						<th>Stats</th>
						<th class="edit"></th>
						<th class="delete"></th>
					</tr>
				</thead>
				<tbody>
					<?php foreach($this->brands as $brand){?>
					<tr>
						<td>
							<a href="<?php echo $this->url('brands/show', array('id' => $brand->id))?>">
								<img src="https://getfavicon.appspot.com/http://www.<?php echo array_pop(explode('@', $brand->from_email))?>?defaulticon=http://userbase.mfcc.cz/img/default-favicon.png" style="margin:-3px 5px 0 0; width:16px; height: 16px;">
								<?php echo $brand->name?>
							</a>
						</td>
						<td>
							<span><?php echo count($brand->campaigns)?> campaigns</span>
						</td>
						<td><a href="<?php echo $this->url('brands/edit', array('id' => $brand->id))?>"><span class="glyphicon glyphicon-pencil"></span> Edit</a></td>
						<td><a href="<?php echo $this->url('brands/delete', array('id' => $brand->id))?>"><span class="glyphicon glyphicon-trash"></span> Delete</a></td>
					</tr>
					<?php }?>
				</tbody>
			</table>

			<a href="<?php echo $this->url('brands')?>" class="btn btn-primary">Go to brands</a>

		</div>

	</div>

</div>

<div class="row">
	<div class="col-md-6">

		<h1><?php echo $this->translate('Total unsubscribe tendency') ?></h1>

		<div class="well">

			<?php echo $this->partial('partials/graph', array('id' => 'unsubYearStats', 'stats' => $this->unsubYearStats, 'colors' => array("'#884646'", "'#B94A48'", "'#333333'")))?>

		</div>

	</div>
	<div class="col-md-6">

		<h1><?php echo $this->translate('Total complain tendency') ?></h1>

		<div class="well">

			<?php echo $this->partial('partials/graph', array('id' => 'complainYearStats', 'stats' => $this->complaintsYearStats, 'colors' => array("'#333333'", "'#B94A48'", "'#333333'")))?>

		</div>

	</div>
</div>

<div class="row">
	<div class="col-md-12">

		<h1>Subaccounts</h1>

		<div class="well brands">

			<table class="table table-striped table-hover fill-head table-responsive">
				<thead>
					<tr>
						<th>Account name</th>
						<th>Status</th>
						<th>Reputation</th>
						<th>Sent total</th>
						<th class="delete"></th>
					</tr>
				</thead>
				<tbody>
					<?php foreach($this->subaccounts as $subaccount){?>
					<tr>
						<td>
							<a href="">
								<?php echo $subaccount['name']?>
							</a>
						</td>
						<td>
							<?php echo $subaccount['status']?>
						</td>
						<td>
							<?php echo $subaccount['reputation']?>
						</td>
						<td>
							<?php echo $subaccount['sent_total']?>
						</td>
						<td><a href=""><span class="glyphicon glyphicon-trash"></span> Delete</a></td>
					</tr>
					<?php }?>
				</tbody>
			</table>

			<a href="<?php echo $this->url('brands')?>" class="btn btn-primary">Go to subaccounts</a>

		</div>
	</div>
</div>

<div class="row">

	<div class="col-md-12">
	    <div class="well">
	    	TODO: Support for Sendgrid and Amazon?
	    </div>
	</div>

</div>

