<script src="<?php echo $this->basePath()?>/js/highcharts/highcharts.js"></script>

<div class="hero-unit">
    <h1><?php echo $this->translate('Dashboard') ?></h1>
    
    <div class="well">
    	TODO: Support for Sendgrid and Amazon?
    </div>

    <h2>Your Mandrill account stats</h2>

    <h4>Basic info</h4>
    <table class="table">
  		<tbody>
  			<tr>
  				<td><b>Reputation</b></td>
  				<td><?php echo $this->mandrillInfo['reputation']?></td>
  				<td><b>Hourly quota</b></td>
  				<td><?php echo $this->mandrillInfo['hourly_quota']?></td>
  				<td><b>Backlog</b></td>
  				<td><?php echo $this->mandrillInfo['backlog']?></td>
  			</tr>
  		</tbody>
	</table>

    <h4>Today stats</h4>
	<?php echo $this->printMandrillStats($this->mandrillInfo['stats']['today'])?>

	<h4>Last 7 days</h4>
	<?php echo $this->printMandrillStats($this->mandrillInfo['stats']['last_7_days'])?>

	<h4>Last 30 days</h4>
	<?php echo $this->printMandrillStats($this->mandrillInfo['stats']['last_30_days'])?>

	<h4>Last 60 days</h4>
	<?php echo $this->printMandrillStats($this->mandrillInfo['stats']['last_60_days'])?>

	<h4>Last 90 days</h4>
	<?php echo $this->printMandrillStats($this->mandrillInfo['stats']['last_90_days'])?>

	<h4>All time</h4>
	<?php echo $this->printMandrillStats($this->mandrillInfo['stats']['all_time'])?>


	<h2>Webhooks status</h2>

	<?php if($this->webhookStatus){?>
		<div class="alert alert-success">
			Webhook is set up.
		</div>
	<?php } else {?>
		<div class="alert alert-error">
			Webhooks won't work on localhost!
		</div>
		<div class="alert alert-block">
			<h4>Warning!</h4>
			Webhook is not set in Mandrill! You wont get any statistics!
			<br />
			<a href="<?php echo $this->url('hooks/set')?>" class="btn btn-primary">Set webhook now!</a>
		</div>
	<?php }?>

	<br />
	<strong>Webhooks formatting help: <a href="http://help.mandrill.com/entries/24466132-Webhook-Format">http://help.mandrill.com/entries/24466132-Webhook-Format</a></strong>

    <h2>Total subscribers</h2>

    <?php echo $this->partial('partials/graph', array('id' => 'totalYearStats', 'stats' => $this->totalYearStats, 'colors' => array("'#468847'", "'#B94A48'", "'#333333'")))?>

    <h2>Total unsubscribe tendency</h2>

    <?php echo $this->partial('partials/graph', array('id' => 'unsubYearStats', 'stats' => $this->unsubYearStats, 'colors' => array("'#884646'", "'#B94A48'", "'#333333'")))?>

    <h2>Total complain tendency</h2>

    <?php echo $this->partial('partials/graph', array('id' => 'complainYearStats', 'stats' => $this->complaintsYearStats, 'colors' => array("'#333333'", "'#B94A48'", "'#333333'")))?>


</div>

<div class="row">

</div>
